id: I53563004
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T23:51:40+00:00'
last_modified: '2022-06-16T03:58:49.543410+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14133
  title: སྦས་དོན་གྱི་ཕྱོགས་ཆ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    A02B:
      image_group_id: I1KG14323
      title: Volume 1 of sbas don gyi phyogs cha/
      total_pages: 238
      order: 1
      base_file: A02B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
